name: 'Parse Command'
description: 'Parse a command from a GitHub event and provide the arguments to following steps'
inputs:
  command:
    description: 'The string that should be parsed'
    required: true
  specification:
    description: 'A full docopt string describing the command that is expected'
    required: true
outputs:
  arguments:
    description: 'The parsed arguments'
  valid:
    description: 'true, if the command matches the specification, false, if it could not be parsed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.specification }}
    - ${{ inputs.command }}
