name: 'Parse Command'
description: 'Parse a command from a GitHub event and provide the arguments to following steps'
inputs:
  command:
    description: 'The string that should be parsed'
    required: true
  docopt:
    description: 'A full docopt string describing the command that is expected'
    required: true
outputs:
  arguments:
    description: 'The parsed arguments'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docopt }}
    - ${{ inputs.command }}
